# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NewCCUDB
                                 A QGIS plugin
 Plugin per a la nova creació de la base de dades del CCU
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-19
        copyright            : (C) 2024 by CCU - Miquel Rodríguez
        email                : miquel.rodriguezj@tecnocampus.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NewCCUDB class from file NewCCUDB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .new_ccu_db import NewCCUDB
    return NewCCUDB(iface)
